spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5999/my-base
  jpa:
    properties:
      hibernate:
        show_sql: true

    hibernate:
      ddl-auto: create